out_dir: results
metric_best: mae
metric_agg: argmin
wandb:
  use: False
  project: alphafold
dataset:
  format: PyG-Alphafold
  name: Alphafold
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: LinearNode+LapPE
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: LinearEdge
  edge_encoder_bn: False
prep:
  exp: False
  exp_deg: 3
  use_exp_edges: False
  add_edge_index: True
  num_virt_node: 6
posenc_LapPE:
  enable: True
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 16
  model: DeepSet
  dim_pe: 32
  layers: 2
  raw_norm_type: none
train:
  mode: custom
  batch_size: 1
  eval_period: 1
  ckpt_period: 100
model:
  type: MultiModel
  loss_fun: l1
  edge_decoding: dot
  graph_pooling: max
gt:
  layer_type: CustomGatedGCN+Exphormer
  layers: 5
  n_heads: 4
  dim_hidden: 64  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.1
  attn_dropout: 0.1
  layer_norm: True
  batch_norm: False
gnn:
  head: default
  layers_pre_mp: 0
  layers_post_mp: 3  # Not used when `gnn.head: san_graph`
  dim_inner: 64  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: False
  act: relu
  dropout: 0.1
  agg: mean
  normalize_adj: False
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.0005
  max_epoch: 150
  scheduler: cosine_with_warmup
  num_warmup_epochs: 10
