out_dir: results
metric_best: accuracy
wandb:
  use: True
  project: malnet
  entity: expand-gnns
dataset:
  format: PyG-MalNetTiny
  name: LocalDegreeProfile
  task: graph
  task_type: classification
  transductive: False
  node_encoder: True
  node_encoder_name: LinearNode
  edge_encoder: True
  edge_encoder_name: DummyEdge
  edge_encoder_bn: False
prep:
  exp: True
  exp_deg: 5
  add_edge_index: True # Set True if you want to add real edges beside expander edges
  num_virt_node: 0 # Set True if you want to add global node connections beside expander edges
posenc_ERN:
  enable: False
  model: Linear
  dim_pe: 8
  layers: 2
train:
  mode: custom
  batch_size: 16
  eval_period: 1
  ckpt_period: 100
model:
  type: MultiModel
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: max
gt:
  layer_type: CustomGatedGCN+Exphormer # some other options: Exphormer, GINE+Exphormer, GINE, GINE__exp
  layers: 5
  n_heads: 4
  dim_hidden: 64  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.15
  attn_dropout: 0.2
  layer_norm: False
  batch_norm: True
gnn:
  head: default
  layers_pre_mp: 1
  layers_post_mp: 3  # Not used when `gnn.head: san_graph`
  dim_inner: 64  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: relu
  dropout: 0.15
  agg: mean
  normalize_adj: False
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.0005
  max_epoch: 150
  scheduler: cosine_with_warmup
  num_warmup_epochs: 10
#optim:
#  optimizer: adam
#  weight_decay: 0.0
#  base_lr: 0.0005
#  max_epoch: 300
#  scheduler: reduce_on_plateau
#  reduce_factor: 0.5
#  schedule_patience: 20
#  min_lr: 1e-5
